#!/usr/bin/env php
<?php
declare(strict_types=1);

use Symfony\Component\Console\Input\ArgvInput;

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$input = new ArgvInput();
$status = $kernel->handle($input)->getStatusCode();
$kernel->terminate($input, $status);
exit($status);
