@php
    $brand = \App\Support\AppSettings::all();
    $u = auth()->user();
    $loc = app()->getLocale();
    $billingNotice = session('plan_notice');
@endphp
<!doctype html>
<html lang="{{ $loc }}" dir="{{ \App\Support\Locales::dir() }}">
<head>
@include('partials.fonts')
@include('partials.pwa')
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex">
<meta name="csrf-token" content="{{ csrf_token() }}"><title>{{ $brand['app_name'] }}</title>
<style>
:root{--bg:#f4f6f9;--card:#fff;--ink:#172033;--muted:#718096;--line:#e4e8ef;--nav:#0f1726;--nav2:#1e2a3d;--blue:#3157d5;--ok:#087f5b;--warn:#9a6509;--danger:#b42318}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:var(--font)}button,input,select,textarea{font:inherit}button{cursor:pointer}
.shell{display:grid;grid-template-columns:255px 1fr;min-height:100vh}.side{background:var(--nav);color:#fff;padding:20px 14px;position:sticky;top:0;height:100vh;overflow:auto}.brand{font-size:21px;font-weight:900;padding:7px 10px 22px}.brand small{display:block;font-size:10px;color:#8d9ab0;margin-top:5px;font-weight:500}.nav{display:grid;gap:3px}.group{font-size:10px;color:#65738a;margin:16px 10px 5px}.nav button,.bottom button{border:0;background:transparent;color:#b8c3d4;text-align:start;border-radius:9px;padding:10px 11px;width:100%}.nav button:hover,.nav button.active{background:var(--nav2);color:#fff}.bottom{border-top:1px solid #273247;margin-top:18px;padding-top:12px}.bottom .lang{padding:10px 11px;font-size:12px;color:#8d9ab0}.bottom .lang a{color:#cbd5e1}.bottom .lang strong{color:#fff}.bottom .lang .sep{margin-inline:6px}
.main{min-width:0;padding:28px}.top{display:flex;justify-content:space-between;align-items:flex-start;gap:15px;margin-bottom:20px}.eyebrow{font-size:11px;color:var(--muted)}h1{font-size:29px;margin:4px 0;font-weight:900}.actions{display:flex;gap:7px;flex-wrap:wrap}.btn{border:1px solid #d4dbe5;background:#fff;color:var(--ink);border-radius:10px;padding:9px 13px;font-weight:700}.btn.primary{background:var(--ink);color:#fff;border-color:var(--ink)}.btn.danger{color:var(--danger)}.btn.small{font-size:11px;padding:6px 9px}
.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.card{background:var(--card);border:1px solid var(--line);border-radius:15px;padding:17px;box-shadow:0 3px 15px rgba(16,24,39,.035)}.metric{font-size:27px;font-weight:900;margin-top:5px}.muted{color:var(--muted);font-size:12px}.grid2{display:grid;grid-template-columns:1.5fr 1fr;gap:13px;margin-top:13px}.section{margin-top:13px}.head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:10px}.head h2{font-size:16px;margin:0}.list{display:grid;gap:7px}.row{display:flex;align-items:center;justify-content:space-between;gap:10px;border:1px solid var(--line);border-radius:10px;padding:11px;background:#fff}.rowmain{min-width:0}.rowtitle{font-weight:750;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.rowsub{font-size:11px;color:var(--muted);margin-top:3px;line-height:1.7}.rowactions{display:flex;gap:4px;flex-shrink:0;flex-wrap:wrap}.pill{display:inline-block;border-radius:999px;padding:4px 8px;background:#edf1f6;font-size:10px;white-space:nowrap}.pill.ok{background:#e9f8f2;color:var(--ok)}.pill.warn{background:#fff6df;color:var(--warn)}.pill.danger{background:#fff0ef;color:var(--danger)}.progress{height:6px;background:#edf0f4;border-radius:20px;overflow:hidden;margin-top:7px}.progress i{display:block;height:100%;background:var(--ink)}
.toolbar{display:flex;gap:8px;justify-content:space-between;align-items:center;margin-bottom:10px;flex-wrap:wrap}.search{width:min(390px,100%);border:1px solid #d6dce5;border-radius:10px;padding:9px 11px}.tablewrap{overflow:auto}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:10px;border-bottom:1px solid var(--line);font-size:12px;text-align:start}.table th{font-size:10px;color:var(--muted)}
.calendar{display:grid;grid-template-columns:repeat(7,1fr);gap:7px}.day{min-height:145px;border:1px solid var(--line);border-radius:11px;background:#fff;padding:9px}.block{background:#eef2ff;border-radius:7px;padding:6px;margin-top:6px;font-size:10px}
.modalback{position:fixed;inset:0;background:#11182799;display:none;align-items:center;justify-content:center;padding:20px;z-index:99}.modalback.show{display:flex}.modal{width:min(760px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:18px;padding:22px}.formgrid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.field.full{grid-column:1/-1}.field label{display:block;font-size:11px;font-weight:800;margin-bottom:5px}.field input,.field select,.field textarea{width:100%;padding:9px;border:1px solid #d6dce5;border-radius:9px;background:#fff}.field textarea{min-height:90px}.modalactions{display:flex;gap:7px;margin-top:15px}
.toast{position:fixed;bottom:20px;inset-inline-start:20px;background:#172033;color:#fff;padding:11px 14px;border-radius:9px;display:none;z-index:120;max-width:min(420px,calc(100% - 40px))}.toast.show{display:block}.toast a{color:#9fb4ff}
.empty{text-align:center;color:#8a95a5;padding:28px}.statgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.hide{display:none!important}
.notice{background:#fff7d6;border:1px solid #efd98a;color:#6b4e00;border-radius:12px;padding:10px 14px;margin-bottom:14px;line-height:1.8;white-space:pre-wrap}
.ai-out h3{font-size:13px;margin:14px 0 6px}.ai-out ul{margin:0;padding-inline-start:18px;line-height:1.9}
input[type=email],input[type=datetime-local],input[type=date],input[type=number]{direction:ltr}
@media(max-width:1050px){.shell{grid-template-columns:80px 1fr}.brand span,.brand small,.nav .txt,.group,.bottom .txt,.bottom .lang{display:none}.brand{text-align:center}.nav button,.bottom button{text-align:center}.cards{grid-template-columns:repeat(2,1fr)}}
@media(max-width:720px){.shell{display:block}.side{height:auto;position:sticky;z-index:20;padding:8px;display:flex;overflow:auto}.brand{padding:9px}.nav{display:flex}.nav button{white-space:nowrap}.bottom{display:none}.main{padding:14px}.top{flex-direction:column}.cards,.grid2,.formgrid,.statgrid{grid-template-columns:1fr}.calendar{grid-template-columns:1fr 1fr}.mobile-links{display:flex!important}}
.mobile-links{display:none;gap:8px;flex-wrap:wrap;margin-bottom:12px;font-size:12px}.mobile-links a{color:var(--blue)}
</style></head>
<body>
<div class="shell"><aside class="side">
<div class="brand">@if($brand['logo'])<img src="{{ $brand['logo'] }}" alt="" style="max-height:40px;max-width:150px;object-fit:contain;display:block;margin-bottom:6px">@endif<span>{{ $brand['app_name'] }}</span><small>{{ $brand['tagline'] }}</small></div>
<nav class="nav">
<button class="active" data-view="today">◉ <span class="txt">{{ __('app.nav.today') }}</span></button><button data-view="tasks">✓ <span class="txt">{{ __('app.nav.tasks') }}</span></button><button data-view="recurring">🔁 <span class="txt">{{ __('app.nav.recurring') }}</span></button><button data-view="inbox">▣ <span class="txt">{{ __('app.nav.inbox') }}</span></button><button data-view="search">⌕ <span class="txt">{{ __('app.nav.search') }}</span></button>
<div class="group">{{ __('app.nav.group_structure') }}</div><button data-view="areas">◈ <span class="txt">{{ __('app.nav.areas') }}</span></button><button data-view="goals">◎ <span class="txt">{{ __('app.nav.goals') }}</span></button><button data-view="projects">▤ <span class="txt">{{ __('app.nav.projects') }}</span></button><button data-view="milestones">◇ <span class="txt">{{ __('app.nav.milestones') }}</span></button>
<div class="group">{{ __('app.nav.group_execution') }}</div><button data-view="daily">☀ <span class="txt">{{ __('app.nav.daily') }}</span></button><button data-view="calendar">□ <span class="txt">{{ __('app.nav.calendar') }}</span></button><button data-view="execution">◷ <span class="txt">{{ __('app.nav.execution') }}</span></button><button data-view="dependencies">⇄ <span class="txt">{{ __('app.nav.dependencies') }}</span></button><button data-view="reminders">◌ <span class="txt">{{ __('app.nav.reminders') }}</span></button><button data-view="failures">⚠ <span class="txt">{{ __('app.nav.failures') }}</span></button>
<div class="group">{{ __('app.nav.group_analysis') }}</div><button data-view="reviews">↻ <span class="txt">{{ __('app.nav.reviews') }}</span></button><button data-view="analytics">◫ <span class="txt">{{ __('app.nav.analytics') }}</span></button><button data-view="reports">▥ <span class="txt">{{ __('app.nav.reports') }}</span></button>
<div class="group">{{ __('app.nav.group_knowledge') }}</div><button data-view="notes">▤ <span class="txt">{{ __('app.nav.notes') }}</span></button><button data-view="decisions">◆ <span class="txt">{{ __('app.nav.decisions') }}</span></button><button data-view="ai-planner">✦ <span class="txt">{{ __('app.nav.ai_planner') }}</span></button><button data-view="ai">✧ <span class="txt">{{ __('app.nav.ai_interactions') }}</span></button><button data-view="pending">⌛ <span class="txt">{{ __('app.nav.pending') }}</span></button><button data-view="activity">◌ <span class="txt">{{ __('app.nav.activity') }}</span></button>
</nav>
<div class="bottom">
<button onclick="location.href='{{ route('account.settings') }}'">🔐 <span class="txt">{{ __('app.nav.settings') }}</span></button>
<button onclick="location.href='{{ route('billing.index') }}'">💳 <span class="txt">{{ __('app.nav.billing') }}</span></button>
@if($brand['support_enabled'] || $u->is_admin)<button onclick="location.href='{{ route('support.index') }}'">💬 <span class="txt">{{ __('app.nav.support') }}</span></button>@endif
@if($u->is_admin)<button onclick="location.href='{{ route('admin.home') }}'">⚙ <span class="txt">{{ __('app.nav.admin') }}</span></button>@endif
<button id="pwa-install" class="hide">⤓ <span class="txt">{{ __('pwa.install') }}</span></button>
<form method="post" action="{{ route('logout') }}">@csrf<button>↪ <span class="txt">{{ __('common.logout') }}</span></button></form>
<div class="lang">@include('partials.lang-switch')</div>
</div>
</aside>
<main class="main">
<div class="mobile-links"><a href="{{ route('account.settings') }}">{{ __('app.nav.settings') }}</a><a href="{{ route('billing.index') }}">{{ __('app.nav.billing') }}</a>@if($brand['support_enabled'])<a href="{{ route('support.index') }}">{{ __('app.nav.support') }}</a>@endif @include('partials.lang-switch')</div>
@if(filled($brand['announcement']))<div class="notice">📢 {{ $brand['announcement'] }}</div>@endif
@if($errors->has('plan'))<div class="notice">{{ $errors->first('plan') }} <a href="{{ route('billing.index') }}">{{ __('billing.see_plans') }}</a></div>@endif
<div class="top"><div><div class="eyebrow">{{ $brand['app_name'] }} · {{ $u->name }} · <span dir="ltr">{{ $u->email }}</span></div><h1 id="title">{{ __('app.nav.today') }}</h1></div><div class="actions"><button class="btn" onclick="loadView(view)">↻ {{ __('common.refresh') }}</button><button class="btn primary" onclick="openCreate()">＋ {{ __('common.add') }}</button></div></div><div id="content"></div></main></div>
<div class="modalback" id="modal"><div class="modal"><div class="head"><h2 id="mtitle"></h2><button class="btn small" onclick="closeModal()" aria-label="{{ __('common.close') }}">×</button></div><div id="mbody"></div></div></div><div id="toast" class="toast" role="status"></div>
<script>
const I18N={t:@json(__('app.js')),nav:@json(__('app.nav')),fields:@json(__('planner.fields')),entities:@json(__('planner.entities')),status:@json(__('planner.task_status')),prio:@json(__('planner.priority')),generic:@json(__('planner.generic_status')),dep:@json(__('planner.dependency_type')),failure:@json(__('planner.failure_reason')),metrics:@json(__('planner.metrics')),reviewType:@json(__('planner.review_type')),recur:{frequency:@json(__('recurrence.frequency')),weekdays:@json(__('recurrence.weekdays')),calendar:@json(__('recurrence.calendar'))},workDays:@json($u->preference('work_days')),activity:@json(__('activity'))};
const LOCALE=@json($loc),TZ=@json($u->preferredTimezone()),INTL=LOCALE==='fa'?'fa-IR':'en-US',BILLING_URL=@json(route('billing.index'));
const csrf=document.querySelector('meta[name=csrf-token]').content,$=id=>document.getElementById(id);let view='today',cache={areas:[],goals:[],projects:[],milestones:[],tasks:[]};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function t(k,r){let s=I18N.t[k]??k;if(r)for(const[a,b]of Object.entries(r))s=s.split(':'+a).join(b);return s}
const num=v=>v==null||v===''?'—':(typeof v==='number'||/^-?\d+(\.\d+)?$/.test(String(v))?Number(v).toLocaleString(INTL,{maximumFractionDigits:2}):String(v));
const fmt=v=>v?new Date(v).toLocaleDateString(INTL,{timeZone:TZ}):'—',fmtDT=v=>v?new Date(v).toLocaleString(INTL,{timeZone:TZ,dateStyle:'short',timeStyle:'short'}):'—';
/* Wall-clock parts of an instant in the user's timezone. */
function tzParts(d){let o={};new Intl.DateTimeFormat('en-US',{timeZone:TZ,hourCycle:'h23',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}).formatToParts(d).forEach(p=>o[p.type]=p.value);return o}
/* ISO instant -> value for <input type=datetime-local> in the user's timezone. */
function toInput(v){if(!v)return'';let o=tzParts(new Date(v));return o.year+'-'+o.month+'-'+o.day+'T'+o.hour+':'+o.minute}
/* <input type=datetime-local> value (user's timezone) -> ISO instant with offset. */
function fromInput(s){if(!s)return null;let[d,h]=s.split('T'),[y,mo,da]=d.split('-').map(Number),[hh,mi]=(h||'00:00').split(':').map(Number),guess=Date.UTC(y,mo-1,da,hh,mi);const off=ms=>{let o=tzParts(new Date(ms));return Date.UTC(+o.year,+o.month-1,+o.day,+o.hour,+o.minute,+o.second)-ms};let ts=guess-off(guess);ts=guess-off(ts);return new Date(ts).toISOString()}
function toast(m,html){let el=$('toast');if(html)el.innerHTML=m;else el.textContent=m;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),html?6000:2600)}
async function api(path,opt={}){let method=(opt.method||'GET').toUpperCase(),h={'Accept':'application/json','X-CSRF-TOKEN':csrf,...(opt.headers||{})};if(method!=='GET'&&method!=='HEAD')h['Content-Type']='application/json';let r=await fetch('/api'+path,{credentials:'same-origin',...opt,headers:h});if(r.status===401){location='/login';throw Error(t('session_expired'))}if(!r.ok){let x={};try{x=await r.json()}catch{}let e=Error(x.message||Object.values(x.errors||{}).flat().join(' ')||t('error'));e.status=r.status;e.upgrade=x.upgrade_url;throw e}return r.status===204?null:r.json()}
function fail(e){if(e.status===402)toast(esc(e.message)+' <a href="'+esc(e.upgrade||BILLING_URL)+'">'+esc(t('see_plans'))+'</a>',true);else toast(e.message)}
async function cacheAll(){let [a,g,p,m,tk]=await Promise.all([api('/areas'),api('/goals'),api('/projects'),api('/milestones'),api('/tasks?per_page=100')]);cache.areas=a.data||a;cache.goals=g.data||g;cache.projects=p.data||p;cache.milestones=m.data||m;cache.tasks=tk.data||tk}
const label=v=>{if(v==null||v==='')return'—';let s=String(v);return I18N.status[s]||I18N.prio[s]||I18N.generic[s]||I18N.failure[s]||s};
function pill(v){let s=String(v||'').toLowerCase(),c=['completed','on_track','on track','done','paid','success'].includes(s)?'ok':['blocked','behind','cancelled','failed','error'].includes(s)?'danger':['waiting','at_risk','at risk','deferred','pending'].includes(s)?'warn':'';return '<span class="pill '+c+'">'+esc(label(v))+'</span>'}
function itemRow(x,kind){let title=(x.recurring_task_id?'🔁 ':'')+(x.title||x.name||x.intent||t('untitled'));return '<div class="row"><div class="rowmain"><div class="rowtitle">'+esc(title)+'</div><div class="rowsub">'+(x.deadline?t('due_on',{date:fmt(x.deadline)}):x.target_date?t('target_on',{date:fmt(x.target_date)}):x.scheduled_at?fmtDT(x.scheduled_at):x.created_at?fmtDT(x.created_at):'')+'</div>'+(x.progress!=null?'<div class="progress"><i style="width:'+Math.min(100,Math.max(0,x.progress))+'%"></i></div>':'')+'</div><div class="rowactions">'+pill(x.status||x.health||x.priority)+(kind==='task'||kind==='project'?'<button class="btn small" title="'+esc(t('att_title'))+'" onclick="attachmentsModal(\''+kind+'\','+x.id+')">📎</button>':'')+(x.recurring_task_id&&!['completed','cancelled'].includes(x.status)?'<button class="btn small" onclick="skipOccurrence('+x.id+')">'+esc(t('skip_occurrence'))+'</button>':'')+'<button class="btn small" onclick="editItem('+x.id+',\''+kind+'\')">'+esc(t('edit'))+'</button><button class="btn small danger" onclick="deleteItem('+x.id+',\''+kind+'\')">'+esc(t('delete'))+'</button></div></div>'}
const F=(n,type,req)=>[n,I18N.fields[n]||n,type,req?1:0];
const schema={
area:{ep:'areas',f:[F('name','text',1),F('type','text'),F('status','text'),F('sort_order','number'),F('description','textarea')]},
goal:{ep:'goals',f:[F('title','text',1),F('area_id','area'),F('status','text'),F('importance','number'),F('weight','number'),F('progress','number'),F('start_date','date'),F('target_date','date'),F('success_criteria','textarea'),F('description','textarea')]},
project:{ep:'projects',f:[F('title','text',1),F('goal_id','goal'),F('status','text'),F('importance','number'),F('weight','number'),F('progress','number'),F('estimated_minutes','number'),F('start_date','date'),F('target_date','date'),F('description','textarea')]},
milestone:{ep:'milestones',f:[F('title','text',1),F('project_id','project',1),F('status','text'),F('weight','number'),F('progress','number'),F('target_date','date')]},
task:{ep:'tasks',f:[F('title','text',1),F('description','textarea'),F('area_id','area'),F('goal_id','goal'),F('project_id','project'),F('milestone_id','milestone'),F('status','status'),F('priority','priority'),F('importance','number'),F('weight','number'),F('progress','number'),F('estimated_minutes','number'),F('deadline','datetime-local'),F('planned_start','datetime-local'),F('planned_end','datetime-local'),F('energy_level','number'),F('focus_level','number'),F('failure_reason','failure')]},
note:{ep:'notes',f:[F('title','text',1),F('content','textarea',1),F('area_id','area'),F('goal_id','goal'),F('project_id','project'),F('task_id','task')]},
decision:{ep:'decisions',f:[F('title','text',1),F('decision','textarea',1),F('rationale','textarea'),F('area_id','area'),F('decided_at','datetime-local',1)]},
schedule:{ep:'schedule-blocks',f:[F('task_id','task'),F('starts_at','datetime-local',1),F('ends_at','datetime-local',1),F('status','text'),F('source','text')]},
reminder:{ep:'reminders',f:[F('task_id','task'),F('type','text',1),F('scheduled_at','datetime-local',1),F('chat_id','text'),F('message','textarea')]}
};
const entityName=k=>I18N.entities[k]||k;
function options(type){let a={area:cache.areas,goal:cache.goals,project:cache.projects,milestone:cache.milestones,task:cache.tasks}[type]||[];return '<select name="__F"><option value="">—</option>'+a.map(x=>'<option value="'+x.id+'">'+esc(x.title||x.name)+'</option>').join('')+'</select>'}
const selectOf=(n,map)=>'<select name="'+n+'"><option value="">—</option>'+Object.entries(map).map(([k,v])=>'<option value="'+esc(k)+'">'+esc(v)+'</option>').join('')+'</select>';
function field(f){let[n,l,ty,req]=f;if(['area','goal','project','milestone','task'].includes(ty))return '<div class="field"><label>'+esc(l)+'</label>'+options(ty).replace('__F',n)+'</div>';if(ty==='status')return '<div class="field"><label>'+esc(l)+'</label>'+selectOf(n,I18N.status)+'</div>';if(ty==='priority')return '<div class="field"><label>'+esc(l)+'</label>'+selectOf(n,I18N.prio)+'</div>';if(ty==='failure')return '<div class="field"><label>'+esc(l)+'</label>'+selectOf(n,I18N.failure)+'</div>';return '<div class="field '+(ty==='textarea'?'full':'')+'"><label>'+esc(l)+'</label>'+(ty==='textarea'?'<textarea name="'+n+'" '+(req?'required':'')+'></textarea>':'<input name="'+n+'" type="'+ty+'" '+(req?'required':'')+'>')+'</div>'}
/* Collect a form, empty -> null, datetime-local -> ISO instant in the user's timezone. */
function collect(form){let d={};for(const el of form.elements){if(!el.name)continue;let v=el.value;d[el.name]=v===''?null:(el.type==='datetime-local'?fromInput(v):v)}return d}
function formHtml(s){return '<form id=f><div class=formgrid>'+s.f.map(field).join('')+'</div><div class=modalactions><button type=button class=btn onclick=closeModal()>'+esc(t('cancel'))+'</button><button class="btn primary">'+esc(t('save'))+'</button></div></form>'}
async function openCreate(kind){if(!kind&&view==='recurring'&&window.recurringForm)return recurringForm();if(!kind&&view==='calendar'&&window.calendarAddBlock)return calendarAddBlock();await cacheAll();if(!kind)kind={tasks:'task',inbox:'task',today:'task',goals:'goal',projects:'project',areas:'area',milestones:'milestone',notes:'note',decisions:'decision',calendar:'schedule',reminders:'reminder'}[view]||'task';let s=schema[kind];if(!s)return;modal(t('new_item',{item:entityName(kind)}),formHtml(s));$('f').onsubmit=async e=>{e.preventDefault();try{await api('/'+s.ep,{method:'POST',body:JSON.stringify(collect(e.target))});closeModal();toast(t('saved'));loadView(view)}catch(x){fail(x)}}}
async function editItem(id,kind){let s=schema[kind];if(!s)return;await cacheAll();let x=await api('/'+s.ep+'/'+id);modal(t('edit_item',{item:entityName(kind)}),formHtml(s));s.f.forEach(([n])=>{let e=document.querySelector('#f [name="'+n+'"]');if(e&&x[n]!=null)e.value=(e.type==='datetime-local'?toInput(x[n]):e.type==='date'?String(x[n]).slice(0,10):x[n])});$('f').onsubmit=async e=>{e.preventDefault();try{await api('/'+s.ep+'/'+id,{method:'PUT',body:JSON.stringify(collect(e.target))});closeModal();toast(t('updated'));loadView(view)}catch(z){fail(z)}}}
async function skipOccurrence(id){if(!confirm(t('skip_confirm')))return;try{await api('/tasks/'+id+'/skip',{method:'POST'});toast(t('saved'));loadView(view)}catch(e){fail(e)}}
async function deleteItem(id,kind){let s=schema[kind];if(!s||!confirm(t('confirm_delete')))return;try{await api('/'+s.ep+'/'+id,{method:'DELETE'});toast(t('deleted'));loadView(view)}catch(e){fail(e)}}
function modal(ti,b){$('mtitle').textContent=ti;$('mbody').innerHTML=b;$('modal').classList.add('show')}function closeModal(){$('modal').classList.remove('show');$('mbody').innerHTML=''}
$('modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
const empty=()=>'<div class=empty>'+esc(t('empty'))+'</div>';
async function loadList(kind,ep=kind){let r=await api('/'+ep+(kind==='tasks'?'?per_page=100':'')),a=r.data||r;if(!Array.isArray(a))a=[];let one=kind.slice(0,-1);$('content').innerHTML='<div class=card><div class=toolbar><input id=q class=search placeholder="'+esc(t('filter_placeholder'))+'" oninput=filterList()><button class="btn primary" onclick="openCreate(\''+one+'\')">＋ '+esc(entityName(one))+'</button></div><div class=list id=rows>'+a.map(x=>itemRow(x,one)).join('')+(a.length?'':empty())+'</div></div>'}
function filterList(){let q=$('q').value.toLowerCase();document.querySelectorAll('#rows .row').forEach(x=>x.style.display=x.textContent.toLowerCase().includes(q)?'flex':'none')}
function metricCards(m){return Object.entries(m).filter(([k,v])=>typeof v!=='object').map(([k,v])=>'<div class=card><div class=muted>'+esc(I18N.metrics[k]||k.replaceAll('_',' '))+'</div><div class=metric>'+esc(num(v))+'</div></div>').join('')}
async function today(){let d=await api('/system/dashboard?days=1'),m=d.metrics,tk=d.recent_tasks||[];$('content').innerHTML='<div class=cards>'+[[I18N.metrics.tasks_created,num(m.tasks_created)],[I18N.metrics.tasks_completed,num(m.tasks_completed)],[I18N.metrics.completion_rate,num(m.completion_rate)],[I18N.metrics.execution_minutes,num(m.execution_minutes)]].map(x=>'<div class=card><div class=muted>'+esc(x[0])+'</div><div class=metric>'+esc(x[1])+'</div></div>').join('')+'</div><div class=grid2><div class=card><div class=head><h2>'+esc(t('recent_tasks'))+'</h2><button class="btn small" onclick="openCreate(\'task\')">＋ '+esc(entityName('task'))+'</button></div><div class=list>'+(tk.map(x=>itemRow(x,'task')).join('')||empty())+'</div></div><div class=card><div class=head><h2>'+esc(I18N.nav.pending)+'</h2></div><div class=list>'+((d.pending_actions||[]).map(x=>'<div class=row><div><b>'+esc(x.intent)+'</b><div class=rowsub>'+fmtDT(x.created_at)+'</div></div>'+pill(x.status)+'</div>').join('')||empty())+'</div></div></div>'}
async function inbox(){let r=await api('/tasks?status=inbox&per_page=100'),a=(r.data||r||[]).filter(x=>x.status==='inbox');$('content').innerHTML='<div class=card><div class=head><h2>'+esc(I18N.nav.inbox)+'</h2><button class="btn primary" onclick="openCreate(\'task\')">＋ '+esc(entityName('task'))+'</button></div><div class=list>'+(a.map(x=>itemRow(x,'task')).join('')||empty())+'</div></div>'}
function mapRows(obj,fn){return Object.entries(obj||{}).map(([k,v])=>fn(k,v)).join('')||empty()}
async function analytics(){let d=await api('/system/dashboard?days=30'),m=d.metrics;$('content').innerHTML='<div class=cards>'+metricCards(m)+'</div><div class=grid2><div class=card><div class=head><h2>'+esc(I18N.metrics.goal_health)+'</h2></div><div class=list>'+mapRows(m.goal_health,(k,v)=>'<div class=row><b>'+esc(label(k))+'</b><span class=pill>'+esc(num(v))+'</span></div>')+'</div></div><div class=card><div class=head><h2>'+esc(I18N.metrics.failure_reasons)+'</h2></div><div class=list>'+mapRows(m.failure_reasons,(k,v)=>'<div class=row><b>'+esc(label(k))+'</b><span class=pill>'+esc(num(v))+'</span></div>')+'</div></div></div>'}
async function reports(p='week'){let d=await api('/system/report?period='+p),m=d.metrics,tk=d.tasks||[];$('content').innerHTML='<div class=card><div class=head><h2>'+esc(t('report_'+p))+'</h2><div class=actions><button class="btn small" onclick="reports(\'day\')">'+esc(t('period_day'))+'</button><button class="btn small" onclick="reports(\'week\')">'+esc(t('period_week'))+'</button><button class="btn small" onclick="reports(\'month\')">'+esc(t('period_month'))+'</button></div></div><div class=statgrid>'+Object.entries(m).filter(([k,v])=>typeof v!=='object').map(([k,v])=>'<div><div class=muted>'+esc(I18N.metrics[k]||k.replaceAll('_',' '))+'</div><strong>'+esc(num(v))+'</strong></div>').join('')+'</div><div class=section><div class=tablewrap><table class=table><tr><th>'+esc(entityName('task'))+'</th><th>'+esc(I18N.fields.status)+'</th><th>'+esc(I18N.fields.priority)+'</th><th>'+esc(I18N.fields.progress)+'</th><th>'+esc(t('estimate_vs_actual'))+'</th></tr>'+tk.map(x=>'<tr><td>'+esc(x.title)+'</td><td>'+pill(x.status)+'</td><td>'+pill(x.priority)+'</td><td>'+esc(num(x.progress))+'%</td><td>'+esc(num(x.estimated_minutes))+' / '+esc(num(x.actual_minutes))+'</td></tr>').join('')+'</table></div></div></div>'}
async function searchView(){$('content').innerHTML='<div class=card><div class=head><h2>'+esc(t('search_title'))+'</h2></div><div class=toolbar><input id=globalq class=search placeholder="'+esc(t('search_placeholder'))+'" onkeydown="if(event.key===\'Enter\')runSearch()"><select id=globalstatus><option value="">'+esc(t('all_statuses'))+'</option>'+Object.entries(I18N.status).map(([k,v])=>'<option value="'+k+'">'+esc(v)+'</option>').join('')+'</select><button class="btn primary" onclick="runSearch()">'+esc(t('search'))+'</button></div><div id=searchresults class=list></div></div>'}
async function runSearch(){let q=($('globalq').value||'').trim();if(q.length<2){toast(t('search_min'));return}let st=$('globalstatus').value;try{let r=await api('/search?q='+encodeURIComponent(q)+(st?'&status='+encodeURIComponent(st):''));let a=r.tasks||[];$('searchresults').innerHTML=a.map(x=>itemRow(x,'task')).join('')||'<div class=empty>'+esc(t('no_results'))+'</div>'}catch(e){fail(e)}}
async function systemList(endpoint,title,render){let r=await api('/system/'+endpoint),a=r.data||r;if(!Array.isArray(a))a=[];$('content').innerHTML='<div class=card><div class=head><h2>'+esc(title)+'</h2></div><div class=list>'+(a.map(render).join('')||empty())+'</div></div>'}
const brief=o=>Object.entries(o||{}).filter(([k,v])=>v!==null&&typeof v!=='object'&&String(v)!=='').slice(0,4).map(([k,v])=>esc(k)+': '+esc(String(v).slice(0,60))).join(' · ');
const renderAI=x=>'<div class=row><div class=rowmain><div class=rowtitle>'+esc(x.intent||'—')+' · '+esc(x.provider||'')+(x.model?' / '+esc(x.model):'')+'</div><div class=rowsub>'+fmtDT(x.created_at)+(x.input_payload&&x.input_payload.focus?' · '+esc(String(x.input_payload.focus).slice(0,120)):'')+(x.output_payload&&typeof x.output_payload.summary==='string'?'<br>'+esc(x.output_payload.summary.slice(0,200)):'')+'</div></div>'+pill(x.status)+'</div>';
const renderPending=x=>'<div class=row><div class=rowmain><div class=rowtitle>#'+x.id+' '+esc(x.intent)+'</div><div class=rowsub>'+fmtDT(x.created_at)+(x.expires_at?' · '+esc(t('expires'))+' '+fmtDT(x.expires_at):'')+'<br>'+brief((x.payload&&x.payload.arguments)||x.payload)+'</div></div>'+pill(x.status)+'</div>';
const renderActivity=x=>'<div class=row><div class=rowmain><div class=rowtitle>'+esc(label(x.action))+' · '+esc(String(x.entity_type||'').split('\\').pop())+(x.entity_id!=null?' #'+esc(x.entity_id):'')+'</div><div class=rowsub>'+fmtDT(x.created_at)+'</div></div></div>';
async function daily(){let r=await api('/system/daily-plans'),a=r.data||[];$('content').innerHTML='<div class=card><div class=head><h2>'+esc(I18N.nav.daily)+'</h2><button class="btn primary" onclick="dailyForm()">＋ '+esc(t('plan_today'))+'</button></div><div class=list>'+(a.map(x=>{let d=String(x.plan_date||x.date||'').slice(0,10);return '<div class=row><div><b>'+esc(fmt(d+'T12:00:00Z'))+'</b><div class=rowsub>'+esc(t('daily_line',{available:num(x.available_minutes||0),planned:num(x.planned_minutes||0),completed:num(x.completed_minutes||0)}))+'</div></div><button class="btn small" onclick="dailyForm(\''+d+'\')">'+esc(t('edit'))+'</button></div>'}).join('')||empty())+'</div></div>'}
async function dailyForm(date){let x=date?await api('/daily-plans/'+date):{};let fld=(n,ty,v)=>'<div class="field'+(ty==='textarea'?' full':'')+'"><label>'+esc(I18N.fields[n]||n)+'</label>'+(ty==='textarea'?'<textarea name='+n+'>'+esc(v??'')+'</textarea>':'<input name='+n+' type='+ty+' value="'+esc(v??'')+'">')+'</div>';modal(I18N.nav.daily,'<form id=f><div class=formgrid>'+(date?'':fld('plan_date','date',tzParts(new Date()).year+'-'+tzParts(new Date()).month+'-'+tzParts(new Date()).day))+fld('available_minutes','number',x.available_minutes)+fld('planned_minutes','number',x.planned_minutes)+fld('completed_minutes','number',x.completed_minutes)+fld('focus_level','number',x.focus_level)+fld('energy_level','number',x.energy_level)+fld('notes','textarea',x.notes)+'</div><div class=modalactions><button class="btn primary">'+esc(t('save'))+'</button></div></form>');$('f').onsubmit=async e=>{e.preventDefault();let d=collect(e.target);try{if(date)await api('/daily-plans/'+date,{method:'PUT',body:JSON.stringify(d)});else await api('/daily-plans',{method:'POST',body:JSON.stringify(d)});closeModal();toast(t('saved'));daily()}catch(z){fail(z)}}}
async function editSchedule(id){let r=await api('/schedule-blocks/'+id);modal(t('edit_item',{item:entityName('schedule')}),'<form id=f><div class=formgrid><div class=field><label>'+esc(I18N.fields.starts_at)+'</label><input name=starts_at type=datetime-local value="'+toInput(r.starts_at)+'"></div><div class=field><label>'+esc(I18N.fields.ends_at)+'</label><input name=ends_at type=datetime-local value="'+toInput(r.ends_at)+'"></div><div class=field><label>'+esc(I18N.fields.status)+'</label><input name=status value="'+esc(r.status||'planned')+'"></div></div><div class=modalactions><button class="btn primary">'+esc(t('save'))+'</button></div></form>');$('f').onsubmit=async e=>{e.preventDefault();try{await api('/schedule-blocks/'+id,{method:'PUT',body:JSON.stringify(collect(e.target))});closeModal();calendar()}catch(x){fail(x)}}}
async function deleteSchedule(id){if(!confirm(t('confirm_delete')))return;try{await api('/schedule-blocks/'+id,{method:'DELETE'});toast(t('deleted'));calendar()}catch(e){fail(e)}}
async function calendar(){await cacheAll();let p=tzParts(new Date()),base=new Date(Date.UTC(+p.year,+p.month-1,+p.day,12)),dow=base.getUTCDay(),shift=LOCALE==='fa'?(dow+1)%7:(dow+6)%7,ds=[];for(let i=0;i<7;i++){let d=new Date(base);d.setUTCDate(base.getUTCDate()-shift+i);ds.push(d)}let bs=await Promise.all(ds.map(d=>api('/schedule-blocks?date='+d.toISOString().slice(0,10)).then(x=>x.data||x||[]).catch(()=>[])));$('content').innerHTML='<div class=card><div class=head><h2>'+esc(t('week_calendar'))+'</h2><button class="btn primary" onclick="openCreate(\'schedule\')">＋ '+esc(entityName('schedule'))+'</button></div><div class=calendar>'+ds.map((d,i)=>'<div class=day><b>'+esc(d.toLocaleDateString(INTL,{weekday:'short',day:'numeric',month:'short',timeZone:'UTC'}))+'</b>'+(Array.isArray(bs[i])?bs[i]:[]).map(b=>'<div class=block>'+fmtDT(b.starts_at)+'<br>'+esc(b.task?.title||t('focus'))+'<div class=rowactions><button class="btn small" onclick="editSchedule('+b.id+')">'+esc(t('edit'))+'</button><button class="btn small danger" onclick="deleteSchedule('+b.id+')" aria-label="'+esc(t('delete'))+'">×</button></div></div>').join('')+'</div>').join('')+'</div></div>'}
function renderAIResult(r){let res=r.result||r,sec=(title,v)=>{if(v==null||v===''||(Array.isArray(v)&&!v.length))return'';let items=Array.isArray(v)?v:[v];return '<h3>'+esc(title)+'</h3><ul>'+items.map(i=>'<li>'+esc(typeof i==='object'?(i.title||i.action||i.recommendation||i.risk||i.description||brief(i)):i)+(typeof i==='object'&&(i.reason||i.priority)?' <span class=muted>'+esc([i.priority,i.reason].filter(Boolean).join(' · '))+'</span>':'')+'</li>').join('')+'</ul>'};return '<div class=ai-out>'+sec(t('ai_summary'),res.summary)+sec(t('ai_risks'),res.risks)+sec(t('ai_recommendations'),res.recommendations)+'<p class=muted>'+esc(t('ai_disclaimer'))+'</p></div>'}
async function aiPlanner(){$('content').innerHTML='<div class=grid2><div class=card><div class=head><h2>'+esc(I18N.nav.ai_planner)+'</h2><span class=muted>'+esc(t('ai_hint'))+'</span></div><textarea id=aitext style="width:100%;min-height:180px;border:1px solid #d6dce5;border-radius:10px;padding:12px" placeholder="'+esc(t('ai_placeholder'))+'"></textarea><div class=modalactions><button class="btn primary" id=aibtn onclick="askAI()">'+esc(t('ai_button'))+'</button></div></div><div class=card><div class=head><h2>'+esc(t('ai_result'))+'</h2></div><div id=aires class=empty>'+esc(t('ai_empty'))+'</div></div></div>'}
async function askAI(){let text=$('aitext').value.trim();if(!text)return;$('aibtn').disabled=true;$('aires').className='';$('aires').textContent=t('ai_thinking');try{let r=await api('/planner/ai-recommendations',{method:'POST',body:JSON.stringify({focus:text})});$('aires').innerHTML=renderAIResult(r)}catch(e){$('aires').textContent=e.message;fail(e)}finally{$('aibtn').disabled=false}}
async function execution(){await cacheAll();let r=await api('/system/execution'),rows=r.data||[];$('content').innerHTML='<div class=card><div class=head><h2>'+esc(I18N.nav.execution)+'</h2><button class="btn primary" onclick="executionForm()">＋ '+esc(t('log_work'))+'</button></div><div class=list>'+(rows.map(x=>'<div class=row><div class=rowmain><div class=rowtitle>'+esc(x.task?.title||'—')+'</div><div class=rowsub>'+fmtDT(x.started_at)+' · '+esc(t('minutes',{count:num(x.duration_minutes||0)}))+' · '+esc(I18N.fields.focus_level)+' '+esc(num(x.focus_level))+' · '+esc(I18N.fields.energy_level)+' '+esc(num(x.energy_level))+'</div><div class=rowsub>'+esc(x.result||x.notes||x.blocker||'')+'</div></div><div class=rowactions><button class="btn small" onclick="executionForm('+x.task_id+','+x.id+')">'+esc(t('edit'))+'</button><button class="btn small danger" onclick="deleteExecution('+x.task_id+','+x.id+')">'+esc(t('delete'))+'</button></div></div>').join('')||empty())+'</div></div>'}
async function executionForm(taskId,id){await cacheAll();let x={};if(id){let r=await api('/tasks/'+taskId+'/execution-logs');x=(r.data||[]).find(v=>v.id==id)||{}}let fld=(n,ty,v,full)=>'<div class="field'+(full?' full':'')+'"><label>'+esc(I18N.fields[n]||n)+'</label>'+(ty==='textarea'?'<textarea name='+n+'>'+esc(v??'')+'</textarea>':'<input name='+n+' type='+ty+' value="'+esc(v??'')+'"'+(ty==='number'?' min=0':'')+'>')+'</div>';modal(id?t('edit_item',{item:entityName('execution')}):t('log_work'),'<form id=f><div class=formgrid>'+(id?'':'<div class=field><label>'+esc(entityName('task'))+'</label>'+options('task').replace('__F','task_id')+'</div>')+fld('started_at','datetime-local',toInput(x.started_at))+fld('ended_at','datetime-local',toInput(x.ended_at))+fld('duration_minutes','number',x.duration_minutes)+fld('focus_level','number',x.focus_level)+fld('energy_level','number',x.energy_level)+fld('result','textarea',x.result,1)+fld('notes','textarea',x.notes,1)+'</div><div class=modalactions><button class="btn primary">'+esc(t('save'))+'</button></div></form>');$('f').onsubmit=async e=>{e.preventDefault();let d=collect(e.target),tid=id?taskId:d.task_id;delete d.task_id;if(!tid){toast(t('choose_task'));return}try{await api('/tasks/'+tid+'/execution-logs'+(id?'/'+id:''),{method:id?'PUT':'POST',body:JSON.stringify(d)});closeModal();toast(t('saved'));execution()}catch(z){fail(z)}}}
async function deleteExecution(taskId,id){if(!confirm(t('confirm_delete')))return;try{await api('/tasks/'+taskId+'/execution-logs/'+id,{method:'DELETE'});toast(t('deleted'));execution()}catch(e){fail(e)}}
async function failures(){let r=await api('/system/failures'),a=r.data||[];$('content').innerHTML='<div class=card><div class=head><h2>'+esc(I18N.nav.failures)+'</h2><button class="btn primary" onclick="logFailure()">＋ '+esc(t('log_failure'))+'</button></div><p class=muted>'+esc(t('failures_readonly'))+'</p><div class=list>'+(a.map(x=>'<div class=row><div><b>'+esc(I18N.failure[x.code]||x.name||x.code)+'</b><div class=rowsub>'+esc(t('preventable'))+': '+esc(label(x.preventable))+' · '+esc(t('severity'))+': '+esc(num(x.severity))+'</div></div></div>').join('')||empty())+'</div></div>'}
async function logFailure(){await cacheAll();modal(t('log_failure'),'<form id=f><div class=formgrid><div class=field><label>'+esc(entityName('task'))+'</label>'+options('task').replace('__F','task_id')+'</div><div class=field><label>'+esc(I18N.fields.reason)+'</label>'+selectOf('failure_reason',I18N.failure)+'</div><div class="field full"><label>'+esc(I18N.fields.description)+'</label><textarea name=description></textarea></div></div><div class=modalactions><button class="btn primary">'+esc(t('save'))+'</button></div></form>');$('f').onsubmit=async e=>{e.preventDefault();let d=collect(e.target),id=d.task_id;if(!id||!d.failure_reason){toast(t('choose_task'));return}try{await api('/tasks/'+id,{method:'PUT',body:JSON.stringify({failure_reason:d.failure_reason,description:d.description,status:'blocked'})});closeModal();toast(t('failure_logged'));failures()}catch(x){fail(x)}}}
async function dependencies(){let r=await api('/system/dependencies'),rows=r.data||[];$('content').innerHTML='<div class=card><div class=head><h2>'+esc(I18N.nav.dependencies)+'</h2><button class="btn primary" onclick="addDependency()">＋ '+esc(entityName('dependency'))+'</button></div><div class=list>'+(rows.map(x=>'<div class=row><div><b>'+esc(x.task?.title||'—')+'</b><div class=rowsub>'+esc(I18N.dep[x.type]||x.type)+' ← '+esc((x.depends_on||x.dependsOn||{}).title||('#'+x.depends_on_task_id))+'</div></div><button class="btn small danger" onclick="deleteDependency('+x.task_id+','+x.id+')">'+esc(t('delete'))+'</button></div>').join('')||empty())+'</div></div>'}
async function deleteDependency(taskId,id){if(!confirm(t('confirm_delete')))return;try{await api('/tasks/'+taskId+'/dependencies/'+id,{method:'DELETE'});toast(t('deleted'));dependencies()}catch(e){fail(e)}}
async function addDependency(){await cacheAll();modal(entityName('dependency'),'<form id=f><div class=formgrid><div class=field><label>'+esc(entityName('task'))+'</label>'+options('task').replace('__F','task_id')+'</div><div class=field><label>'+esc(I18N.fields.depends_on_task_id)+'</label>'+options('task').replace('__F','depends_on_task_id')+'</div><div class=field><label>'+esc(I18N.fields.type)+'</label>'+selectOf('type',I18N.dep)+'</div></div><div class=modalactions><button class="btn primary">'+esc(t('save'))+'</button></div></form>');$('f').onsubmit=async e=>{e.preventDefault();let d=collect(e.target);try{await api('/tasks/'+d.task_id+'/dependencies',{method:'POST',body:JSON.stringify({depends_on_task_id:d.depends_on_task_id,type:d.type||'requires'})});closeModal();toast(t('saved'));dependencies()}catch(x){fail(x)}}}
async function reviews(){let r=await api('/reviews'),a=r.data||[];$('content').innerHTML='<div class=card><div class=head><h2>'+esc(I18N.nav.reviews)+'</h2><button class="btn primary" onclick="generateReview()">＋ '+esc(t('generate_review'))+'</button></div><div class=list>'+(a.map(x=>'<div class=row><div><b>'+esc(I18N.reviewType[x.type]||x.type)+'</b><div class=rowsub>'+esc(t('range',{from:fmt(x.period_start),to:fmt(x.period_end)}))+' · '+esc(x.summary||'')+'</div></div></div>').join('')||empty())+'</div></div>'}
async function generateReview(){try{await api('/reviews/generate',{method:'POST',body:JSON.stringify({type:'weekly'})});toast(t('review_generated'));loadView('reviews')}catch(e){fail(e)}}
async function loadView(v){view=v;$('title').textContent=I18N.nav[{'ai-planner':'ai_planner',ai:'ai_interactions'}[v]||v]||v;try{
if(v==='today')return today();if(v==='inbox')return inbox();if(v==='search')return searchView();if(v==='ai-planner')return aiPlanner();if(v==='analytics')return analytics();if(v==='reports')return reports('week');if(v==='daily')return daily();if(v==='calendar')return window.calendarView?calendarView():calendar();if(v==='recurring')return recurringView();if(v==='dependencies')return dependencies();
if(v==='execution')return execution();if(v==='failures')return failures();if(v==='reviews')return reviews();
if(v==='ai')return systemList('ai-interactions',I18N.nav.ai_interactions,renderAI);if(v==='pending')return systemList('pending-actions',I18N.nav.pending,renderPending);if(v==='activity')return window.activityTimeline?activityTimeline():systemList('activity',I18N.nav.activity,renderActivity);
if(['tasks','goals','projects','areas','milestones','reminders','notes','decisions'].includes(v))return loadList(v);
}catch(e){$('content').innerHTML='<div class=card><div style="color:#b42318">'+esc(e.message)+'</div></div>'}}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');loadView(b.dataset.view)});
document.addEventListener('DOMContentLoaded',()=>loadView(view));
let pwaPrompt=null;addEventListener('beforeinstallprompt',e=>{e.preventDefault();pwaPrompt=e;$('pwa-install').classList.remove('hide')});$('pwa-install').onclick=async()=>{if(!pwaPrompt)return;pwaPrompt.prompt();await pwaPrompt.userChoice;pwaPrompt=null;$('pwa-install').classList.add('hide')};
</script>
<script src="{{ asset('js/planner-calendar.js') }}?v={{ @filemtime(public_path('js/planner-calendar.js')) }}"></script>
<script src="{{ asset('js/planner-ai.js') }}?v={{ @filemtime(public_path('js/planner-ai.js')) }}"></script></body></html>
