@extends('layouts.page')
@section('title', __('admin.access.title'))
@push('styles')
.token{background:#fff7d6;border:1px solid #e8d58b;padding:12px;border-radius:10px;word-break:break-all;direction:ltr}.modal{display:none;position:fixed;inset:0;background:#0007;align-items:center;justify-content:center;padding:20px;z-index:50}.modal.show{display:flex}.box{background:#fff;border-radius:16px;padding:22px;width:min(520px,100%)}.actions{display:flex;gap:7px;margin-top:14px}
@endpush
@section('content')
<h1>{{ __('admin.access.title') }}</h1>
<p class="muted">{{ __('admin.access.subtitle') }}</p>
<div class="card"><div class="row" style="justify-content:space-between"><h2>{{ __('admin.access.users') }}</h2><button class="btn primary" onclick="userForm()">{{ __('admin.access.add_user') }}</button></div><div id="users" class="tbl"></div></div>
<div class="card"><div class="row" style="justify-content:space-between"><h2>{{ __('admin.access.tokens') }}</h2><button class="btn primary" onclick="tokenForm()">{{ __('admin.access.add_token') }}</button></div><div id="tokens"></div></div>
<div class="modal" id="modal"><div class="box" id="box"></div></div>
@endsection
@push('scripts')
<script>
const T=@json(__('admin.access')),csrf=document.querySelector('meta[name=csrf-token]')?.content;
async function api(p,o={}){let h={'Accept':'application/json','X-CSRF-TOKEN':csrf,...(o.headers||{})};if(o.method&&o.method!=='GET')h['Content-Type']='application/json';let r=await fetch('/api'+p,{...o,headers:h,credentials:'same-origin'});if(!r.ok){let x={};try{x=await r.json()}catch{};throw Error(x.message||Object.values(x.errors||{}).flat().join(' ')||T.error)}return r.status===204?null:r.json()}
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function load(){let u=await api('/admin/users'),t=await api('/admin/tokens');document.querySelector('#users').innerHTML='<table><tr><th>'+esc(T.name)+'</th><th>'+esc(T.email)+'</th><th>'+esc(T.role)+'</th><th>'+esc(T.status)+'</th><th></th></tr>'+u.map(x=>'<tr><td>'+esc(x.name)+'</td><td class=ltr>'+esc(x.email)+'</td><td>'+esc(x.is_admin?T.admin:T.user)+'</td><td>'+esc(x.is_active?T.active:T.inactive)+'</td><td><button class="btn sm" onclick="editUser('+x.id+')">'+esc(T.edit)+'</button> <button class="btn sm danger" onclick="delUser('+x.id+')">'+esc(T.delete)+'</button></td></tr>').join('')+'</table>';document.querySelector('#tokens').innerHTML=t.map(x=>'<div style="padding:10px;border-bottom:1px solid #eee"><b>'+esc(x.name)+'</b> · <span class=ltr>'+esc(x.token_prefix)+'…</span> · '+esc(x.last_used_at||T.never_used)+' <button class="btn sm danger" onclick="revoke('+x.id+')">'+esc(T.revoke)+'</button></div>').join('')||'<p class=muted>'+esc(T.no_tokens)+'</p>'}
function show(h){document.querySelector('#box').innerHTML=h;document.querySelector('#modal').classList.add('show')}function closeModal(){document.querySelector('#modal').classList.remove('show')}
function userForm(x={}){show('<h2>'+esc(x.id?T.edit:T.new_user)+'</h2><form id=f><div class=field><label>'+esc(T.name)+'</label><input name=name required value="'+esc(x.name||'')+'"></div><div class=field><label>'+esc(T.email)+'</label><input name=email type=email required value="'+esc(x.email||'')+'"></div><div class=field><label>'+esc(T.password)+' '+esc(x.id?T.password_keep:'')+'</label><input name=password type=password '+(x.id?'':'required')+'></div><label class=check><input type=checkbox name=is_admin '+(x.is_admin?'checked':'')+'> '+esc(T.admin)+'</label><label class=check><input type=checkbox name=is_active '+(x.is_active!==false?'checked':'')+'> '+esc(T.active)+'</label><div class=actions><button class="btn primary">'+esc(T.save)+'</button><button type=button class=btn onclick=closeModal()>'+esc(T.cancel)+'</button></div></form>');document.querySelector('#f').onsubmit=async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));d.is_admin=e.target.is_admin.checked;d.is_active=e.target.is_active.checked;if(!d.password)delete d.password;try{await api('/admin/users'+(x.id?'/'+x.id:''),{method:x.id?'PUT':'POST',body:JSON.stringify(d)});closeModal();load()}catch(z){alert(z.message)}}}
async function editUser(id){let u=await api('/admin/users');userForm(u.find(x=>x.id===id))}
async function delUser(id){if(confirm(T.confirm_delete_user)){try{await api('/admin/users/'+id,{method:'DELETE'});load()}catch(e){alert(e.message)}}}
function tokenForm(){show('<h2>'+esc(T.new_token)+'</h2><form id=f><div class=field><label>'+esc(T.token_name)+'</label><input name=name required placeholder="Telegram / Integration"></div><div class=field><label>'+esc(T.expires)+'</label><input name=expires_at type=datetime-local></div><div class=actions><button class="btn primary">'+esc(T.create)+'</button><button type=button class=btn onclick=closeModal()>'+esc(T.cancel)+'</button></div></form>');document.querySelector('#f').onsubmit=async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));d.expires_at=d.expires_at?new Date(d.expires_at).toISOString():null;try{let r=await api('/admin/tokens',{method:'POST',body:JSON.stringify(d)});show('<h2>'+esc(T.token_created)+'</h2><p>'+esc(T.token_once)+'</p><div class=token>'+esc(r.token)+'</div><div class=actions><button class="btn primary" onclick="closeModal();load()">'+esc(T.close)+'</button></div>')}catch(z){alert(z.message)}}}
async function revoke(id){if(confirm(T.confirm_revoke)){await api('/admin/tokens/'+id,{method:'DELETE'});load()}}
load();
</script>
@endpush
